/*
 * The sample smart contract
 */

package main

/* Imports
 * 4 utility libraries for formatting, handling bytes, reading and writing JSON, and string manipulation
 * 2 specific Hyperledger Fabric specific libraries for Smart Contracts
 */
import (
	// "bytes"
	// "encoding/json"
	 "fmt"
	// "strconv"

	"github.com/hyperledger/fabric/core/chaincode/shim"
	sc "github.com/hyperledger/fabric/protos/peer"
	//"time"
)

// sample Id generator starts at 4
var id = 0
var partId = 0


// Define the Smart Contract structure
type SmartContract struct {
}


// Define the car structure.  Structure tags are used by encoding/json library
{{#assets}}
type {{assetName}} struct {
	{{#atributes}}
	{{name}}   {{type}}  `json:"{{name}}"`
	{{/atributes}}
}


func New{{assetName}}({{#atributes}} {{name}}Arg {{type}}{{^last}}, {{/last}} {{/atributes}}) *{{assetName}} {

	return &{{assetName}}{

		{{#atributes}}
		{{name}}:   {{name}}Arg,
		{{/atributes}}
	}
}
{{/assets}}


/*
 * The Init method is called when the Smart Contract "fabcar" is instantiated by the blockchain network
 * Best practice is to have any Ledger initialization in separate function -- see initLedger()
 */
func (s *SmartContract) Init(APIstub shim.ChaincodeStubInterface) sc.Response {
	fmt.Printf("Initializating...")
	return shim.Success(nil)
}

/*
 * The Invoke method is called as a result of an application request to run the Smart Contract "fabcar"
 * The calling application program has also specified the particular smart contract function to be called, with arguments
 */
func (s *SmartContract) Invoke(APIstub shim.ChaincodeStubInterface) sc.Response {

	// Retrieve the requested Smart Contract function and arguments
	function, args := APIstub.GetFunctionAndParameters()
	// Route to the appropriate handler function to interact with the ledger appropriately
	
	{{#funcs}}{{^first}}else {{/first}}if function == "{{funcName}}" {
		return s.{{funcName}}(APIstub{{#args}}, args{{/args}})
	} {{/funcs}}

	return shim.Error("Invalid Smart Contract function name.")
}
{{#funcs}}
func (s *SmartContract) {{funcName}}(APIstub shim.ChaincodeStubInterface{{#args}}, args[]string{{/args}}) sc.Response {
	/**
	* This is only a template, it is autogenerated.
	*/
	
	return shim.Success(nil)
}
{{/funcs}}



// The main function is only relevant in unit test mode. Only included here for completeness.
func main() {

	// Create a new Smart Contract
	err := shim.Start(new(SmartContract))
	if err != nil {
		fmt.Printf("Error creating new Smart Contract: %s", err)
	}
}
